version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: psl_postgres
    environment:
      POSTGRES_DB: psl_spotlight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Meka2000
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: psl_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/psl_spotlight
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Meka2000
    restart: always

volumes:
  pgdata: